### ISSUE TITLE
[epic] support region analytics

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#131]
once region is implemented, the next step is to support region analytics. This includes (in prioritized order and incomplete for now):

- [ ] region spectral profile
- [ ] moment image generator
- [ ] pv image generator
- [ ] region spatial profile
- [ ] region statistics
- [ ] region histogram
