### ISSUE TITLE
Capabilities to generate a publication-quality image plot

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#42]
This is a ~draft~ checklist for the initial release of the scripting interface (along with documentation and examples) in v4-beta1. The target is to provide necessary functions for generating a publication-quality plot. These should be documented for both python scripting and code snippets

- [ ] support  regions/annotations (https://github.com/CARTAvis/carta-python/issues/80)
- [ ] Generate contours (https://github.com/CARTAvis/carta-python/issues/62)
- [ ] Set FOV in image pixels or angular size in the image view (https://github.com/CARTAvis/carta-python/issues/57)
- [ ] Set image view styling (grid, coordinate system, label, title, beam, etc)
- [ ] Generate vector field overlay (https://github.com/CARTAvis/carta-python/issues/79)
- [x] Load an image
- [x] Trigger image spatial matching
- [x] Trigger image spectral matching
- [x] Trigger raster scale matching
- [x] Set spatial matching reference image
- [x] Set spectral matching reference image
- [x] Set raster scale matching reference image
- [x] Set a (inverted) colormap
- [x] Set a scaling function for pixel value to colormap mapping
- [x] Set a pixel value range for colormap mapping
- [x] Set bias and contrast of the colormap mapping
- [x] Set image view size and aspect ratio
- [x] Set channel of an image
- [x] Set polarization of an image
- [ ] Center an image feature in the image view by image coordinates or world coordinates (https://github.com/CARTAvis/carta-python/issues/56)
- [ ] Set contour styling (https://github.com/CARTAvis/carta-python/issues/62)
- [ ] Set colorbar orientation (https://github.com/CARTAvis/carta-python/issues/78)
- [ ] Set colorbar styling (width, tick labels, etc) (https://github.com/CARTAvis/carta-python/issues/78)
- [ ] Set vector field overlay styling (https://github.com/CARTAvis/carta-python/issues/79)
- [ ] Set PNG export resolution (https://github.com/CARTAvis/carta-python/issues/81)
- [ ] Set single panel mode or configure the grid layout in the multi-panel mode (https://github.com/CARTAvis/carta-python/issues/75)
- [ ] Set a clip level for colormap mapping (https://github.com/CARTAvis/carta-python/issues/77)
- [ ] Load multiple images (https://github.com/CARTAvis/carta-python/issues/76)
- [ ] ~~(good to have) enable RGB image blending~~

**Comment by Kechil** [comment]
Hi @Jordatious. I've assigned you to this to help with the requirements - best way of presenting the documentation to the users,

**Comment by confluence** [comment]
This issue is divided into several subtasks:

* Checking the status of each feature in the wrapper (implemented as a high-level function / no high-level function but is achievable through the low-level action interface / needs a frontend change).
* Creating appropriate issues in the wrapper and/or frontend for adding the missing features.
* Documenting each feature in a cookbook of code examples, to be added to the wrapper documentation in this repo.

There are some companion tasks which are not wrapper tasks and I think should be separate issues in the frontend repo:

* Documenting the same examples as JS snippets (the other CARTA scripting interface). These probably won't be very similar to the wrapper examples because there are no high-level functions in the snippet interface, whereas we aim to have high-level wrapper functions implemented for all common tasks.
* Adding inline comments / docstrings (?) to the frontend actions, so that a common API which is included both in the wrapper and the snippet instructions can be generated programmatically. Integrating this API into the documentation should perhaps be a separate issue.

Related:

* #36 would let us call snippets from the wrapper, which may have helpful applications (e.g. reusing existing snippet scripts from Python; adding UI widgets to an interactive session from Python).
* It would be nice to add frontend functions to allow the script developer to explore the store tree dynamically at runtime (return a list of actions, properties and substores available on a particular store; check if an object exists; retrieve the docstring of an action or property, etc.).

**Comment by kswang1029** [comment]
@Jordatious help wanted. If you have time, please help on identifying what functions/features are required for generating a "publication-quality" image plot. The above list collects a set of features for the purpose but it may not be complete.

**Comment by Jordatious** [comment]
Sure @kswang1029, I'll check it out. I assume you mean [this list](https://github.com/CARTAvis/carta-python/issues/42#issue-1350244683).

**Comment by Jordatious** [comment]
Hey @kswang1029, I hope you don't mind, but I've ordered the above list by feature priority. Below those already completed I've also ordered by priority, but these I consider to be those that could be later implemented, if necessary. Down the very bottom, I've placed features that would be nice, but that can be overcome with a bit of trial and error.

**Comment by Jordatious** [comment]
In general I think all of these items are necessary to address.
